version: '3.8'

services:
  mongo:
    image: mongo:latest
    container_name: project-mongo
    ports:
      - "27017:27017"
    volumes:
      - mongo-data:/data/db
    deploy:
      resources:
        limits:
          memory: 512M  # Giới hạn sử dụng RAM



  backend:
    build:
      context: ./BE_Node
    container_name: project-backend
    ports:
      - "8000:8000"
    volumes:
      - ./BE_Node/:/app
    links:
      - mongo
    depends_on:
      - mongo
    deploy:
      resources:
        limits:
          memory: 1G  # Giới hạn sử dụng RAM

  frontend:
    build:
      context: ./nckh-fe
    container_name: project-frontend
    ports:
      - "3000:80"  # Chỉnh sửa port để phù hợp với Nginx
    volumes:
      - ./nckh-fe/:/app
    depends_on:
      - backend
    deploy:
      resources:
        limits:
          memory: 512M  # Giới hạn sử dụng RAM

volumes:
  mongo-data:
